//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 03:13:54 오후 KST 
//


package net.herit.iot.onem2m.resource;


import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import net.herit.iot.message.onem2m.OneM2mRequest.OPERATION;
import net.herit.iot.onem2m.core.util.OneM2MException;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}resource">
 *       &lt;sequence>
 *         &lt;element name="accessControlPolicyIDs" type="{http://www.onem2m.org/xml/protocols}acpType" minOccurs="0"/>
 *         &lt;element name="cseType" type="{http://www.onem2m.org/xml/protocols}cseTypeID" minOccurs="0"/>
 *         &lt;element name="CSE-ID" type="{http://www.onem2m.org/xml/protocols}ID"/>
 *         &lt;element name="supportedResourceType">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.onem2m.org/xml/protocols}resourceType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pointOfAccess" type="{http://www.onem2m.org/xml/protocols}poaList"/>
 *         &lt;element name="nodeLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}remoteCSE"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}node"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}AE"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}container"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}group"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}accessControlPolicy"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}mgmtCmd"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}locationPolicy"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}statsConfig"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}statsCollect"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}request"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}delivery"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}schedule"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}m2mServiceSubscriptionProfile"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}serviceSubscribedAppRule"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accessControlPolicyIDs",
    "cseType",
    "cseid",
    "supportedResourceType",
    "pointOfAccess",
    "nodeLink",
    "e2ESecInfo",			// XSD-2.7.0
    "childResource",
  //  "remoteCSEOrNodeOrAE" XSD-1.6.0
    "remoteCSEOrRemoteCSEAnncOrNode"	// XSD-2.7.0
})
//@XmlRootElement(name = "CSEBase")
//@XmlRootElement(name = "csb")
@XmlRootElement(name = Naming.CSEBASE_SN)  // XSD-1.6.0
public class CSEBase
    extends Resource
{

//	public final static String SCHEMA_LOCATION = "CDT-CSEBase-v1_2_0.xsd";
//	public final static String SCHEMA_LOCATION = "CDT-CSEBase-v1_6_0.xsd";
	public final static String SCHEMA_LOCATION = "CDT-CSEBase-v2_7_0.xsd";
	
    @XmlList
    @XmlElement(name = Naming.ACCESSCONTROLPOLICYIDS_SN)
    protected List<String> accessControlPolicyIDs;
    @XmlElement(name = Naming.CSETYPE_SN)
    protected Integer cseType;
    //@XmlElement(name = "CSE-ID", required = true)
    @XmlElement(name = Naming.CSEID_SN)
    protected String cseid;
    @XmlList
    //@XmlElement(required = true)
    @XmlElement(name = Naming.SUPPORTEDRESOURCETYPE_SN)
    protected List<Integer> supportedResourceType;
    @XmlList
    //@XmlElement(required = true)
    @XmlElement(name = Naming.POINTOFACCESS_SN)
    protected List<String> pointOfAccess;
    @XmlSchemaType(name = "anyURI")
    @XmlElement(name = Naming.NODELINK_SN)
    protected String nodeLink;
    @XmlElement(name = Naming.E2ESECINFO_SN)
    protected E2ESecInfo e2ESecInfo;
    @XmlElement(name = Naming.CHILDRESOURCE_SN)
    protected List<ChildResourceRef> childResource;
    @XmlElements({
     /*  below CDT-2.7.0  
      * @XmlElement(name = "remoteCSE", namespace = "http://www.onem2m.org/xml/protocols", type = RemoteCSE.class),
        @XmlElement(name = "node", namespace = "http://www.onem2m.org/xml/protocols", type = Node.class),
        @XmlElement(name = "AE", namespace = "http://www.onem2m.org/xml/protocols", type = AE.class),
        @XmlElement(name = "container", namespace = "http://www.onem2m.org/xml/protocols", type = Container.class),
        @XmlElement(name = "group", namespace = "http://www.onem2m.org/xml/protocols", type = Group.class),
        @XmlElement(name = "accessControlPolicy", namespace = "http://www.onem2m.org/xml/protocols", type = AccessControlPolicy.class),
        @XmlElement(name = "subscription", namespace = "http://www.onem2m.org/xml/protocols", type = Subscription.class),
        @XmlElement(name = "mgmtCmd", namespace = "http://www.onem2m.org/xml/protocols", type = MgmtCmd.class),
        @XmlElement(name = "locationPolicy", namespace = "http://www.onem2m.org/xml/protocols", type = LocationPolicy.class),
        @XmlElement(name = "statsConfig", namespace = "http://www.onem2m.org/xml/protocols", type = StatsConfig.class),
        @XmlElement(name = "statsCollect", namespace = "http://www.onem2m.org/xml/protocols", type = StatsCollect.class),
        @XmlElement(name = "request", namespace = "http://www.onem2m.org/xml/protocols", type = Request.class),
        @XmlElement(name = "delivery", namespace = "http://www.onem2m.org/xml/protocols", type = Delivery.class),
        @XmlElement(name = "schedule", namespace = "http://www.onem2m.org/xml/protocols", type = Schedule.class),
        @XmlElement(name = "m2mServiceSubscriptionProfile", namespace = "http://www.onem2m.org/xml/protocols", type = M2MServiceSubscriptionProfile.class),
        @XmlElement(name = "serviceSubscribedAppRule", namespace = "http://www.onem2m.org/xml/protocols", type = ServiceSubscribedAppRule.class)   */
    	@XmlElement(name = "remoteCSE", namespace = "http://www.onem2m.org/xml/protocols", type = RemoteCSE.class),
        @XmlElement(name = "remoteCSEAnnc", namespace = "http://www.onem2m.org/xml/protocols", type = RemoteCSEAnnc.class),
        @XmlElement(name = "node", namespace = "http://www.onem2m.org/xml/protocols", type = Node.class),
        @XmlElement(name = "AE", namespace = "http://www.onem2m.org/xml/protocols", type = AE.class),
        @XmlElement(name = "container", namespace = "http://www.onem2m.org/xml/protocols", type = Container.class),
        @XmlElement(name = "group", namespace = "http://www.onem2m.org/xml/protocols", type = Group.class),
        @XmlElement(name = "accessControlPolicy", namespace = "http://www.onem2m.org/xml/protocols", type = AccessControlPolicy.class),
        @XmlElement(name = "subscription", namespace = "http://www.onem2m.org/xml/protocols", type = Subscription.class),
        @XmlElement(name = "mgmtCmd", namespace = "http://www.onem2m.org/xml/protocols", type = MgmtCmd.class),
        @XmlElement(name = "locationPolicy", namespace = "http://www.onem2m.org/xml/protocols", type = LocationPolicy.class),
        @XmlElement(name = "statsConfig", namespace = "http://www.onem2m.org/xml/protocols", type = StatsConfig.class),
        @XmlElement(name = "statsCollect", namespace = "http://www.onem2m.org/xml/protocols", type = StatsCollect.class),
        @XmlElement(name = "request", namespace = "http://www.onem2m.org/xml/protocols", type = Request.class),
        @XmlElement(name = "delivery", namespace = "http://www.onem2m.org/xml/protocols", type = Delivery.class),
        @XmlElement(name = "schedule", namespace = "http://www.onem2m.org/xml/protocols", type = Schedule.class),
        @XmlElement(name = "m2mServiceSubscriptionProfile", namespace = "http://www.onem2m.org/xml/protocols", type = M2MServiceSubscriptionProfile.class),
        @XmlElement(name = "serviceSubscribedAppRule", namespace = "http://www.onem2m.org/xml/protocols", type = ServiceSubscribedAppRule.class),
        @XmlElement(name = "role", namespace = "http://www.onem2m.org/xml/protocols", type = Role.class),
        @XmlElement(name = "token", namespace = "http://www.onem2m.org/xml/protocols", type = Token.class),
        @XmlElement(name = "sg_flexContainerResource", namespace = "http://www.onem2m.org/xml/protocols", type = FlexContainerResource.class)
    })
    protected List<Object> remoteCSEOrRemoteCSEAnncOrNode;

    /**
     * Gets the value of the accessControlPolicyIDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessControlPolicyIDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessControlPolicyIDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAccessControlPolicyIDs() {
//        if (accessControlPolicyIDs == null) {
//            accessControlPolicyIDs = new ArrayList<String>();
//        }
        return this.accessControlPolicyIDs;
    }
    
    public void addAccessControlPolicyIDs(String acpid) {
    	if (accessControlPolicyIDs == null) {
    		accessControlPolicyIDs = new ArrayList<String>();
    	}
    	this.accessControlPolicyIDs.add(acpid);
    }

    /**
     * Gets the value of the cseType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCseType() {
        return cseType;
    }

    /**
     * Sets the value of the cseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCseType(Integer value) {
        this.cseType = value;
    }

    /**
     * Gets the value of the cseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSEID() {
        return cseid;
    }

    /**
     * Sets the value of the cseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSEID(String value) {
        this.cseid = value;
    }

    /**
     * Gets the value of the supportedResourceType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedResourceType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedResourceType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getSupportedResourceType() {
//        if (supportedResourceType == null) {
//            supportedResourceType = new ArrayList<Integer>();
//        }
        return this.supportedResourceType;
    }
    
    public void addSupportedResourceType(Integer resourceType) {
    	if (supportedResourceType == null) {
    		supportedResourceType = new ArrayList<Integer>();
    	}
    	supportedResourceType.add(resourceType);
    }

    /**
     * Gets the value of the pointOfAccess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pointOfAccess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPointOfAccess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPointOfAccess() {
//    	if (pointOfAccess == null) {
//    		pointOfAccess = new ArrayList<String>();
//    	}
    	return this.pointOfAccess;
    }
    public void addPointOfAccess(String poa) {
    	if (pointOfAccess == null) {
    		pointOfAccess = new ArrayList<String>();
    	}
    	pointOfAccess.add(poa);
    }

    /**
     * Gets the value of the nodeLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeLink() {
        return nodeLink;
    }

    /**
     * Sets the value of the nodeLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeLink(String value) {
        this.nodeLink = value;
    }
    
    /**
     * Gets the value of the e2ESecInfo property.
     * 
     * @return
     *     possible object is
     *     {@link E2ESecInfo }
     *     
     */
    public E2ESecInfo getE2ESecInfo() {
        return e2ESecInfo;
    }

    /**
     * Sets the value of the e2ESecInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link E2ESecInfo }
     *     
     */
    public void setE2ESecInfo(E2ESecInfo value) {
        this.e2ESecInfo = value;
    }

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
//        if (childResource == null) {
//            childResource = new ArrayList<ChildResourceRef>();
//        }
        return this.childResource;
    }

    public void addChildResource(ChildResourceRef ch) {
    	if (childResource == null) {
    		childResource = new ArrayList<ChildResourceRef>();
    	}
    	this.childResource.add(ch);
    }
    
    /**
     * Gets the value of the remoteCSEOrNodeOrAE property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remoteCSEOrNodeOrAE property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoteCSEOrNodeOrAE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RemoteCSE }
     * {@link Node }
     * {@link AE }
     * {@link Container }
     * {@link Group }
     * {@link AccessControlPolicy }
     * {@link Subscription }
     * {@link MgmtCmd }
     * {@link LocationPolicy }
     * {@link StatsConfig }
     * {@link StatsCollect }
     * {@link Request }
     * {@link Delivery }
     * {@link Schedule }
     * {@link M2MServiceSubscriptionProfile }
     * {@link ServiceSubscribedAppRule }
     * 
     * 
     */
    public List<Object> getRemoteCSEOrRemoteCSEAnncOrNode() {
//    	if (remoteCSEOrRemoteCSEAnncOrNode == null) {
//        	remoteCSEOrRemoteCSEAnncOrNode = new ArrayList<Object>();
//    	}
    	return this.remoteCSEOrRemoteCSEAnncOrNode;
    }

    public void addRemoteCSEOrRemoteCSEAnncOrNode(Object res) {
    	if (remoteCSEOrRemoteCSEAnncOrNode == null) {
    		remoteCSEOrRemoteCSEAnncOrNode = new ArrayList<Object>();
    	}
    	this.remoteCSEOrRemoteCSEAnncOrNode.add(res);
    }
    
    
}
