//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 03:14:16 오후 KST 
//


package net.herit.iot.onem2m.resource;


import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.Map.Entry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * XSD-1.6.0
 * <p>Java class for filterCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filterCriteria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createdBefore" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="createdAfter" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="modifiedSince" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="unmodifiedSince" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="stateTagSmaller" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="stateTagBigger" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="expireBefore" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="expireAfter" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="labels" type="{http://www.onem2m.org/xml/protocols}labels" minOccurs="0"/>
 *         &lt;element name="resourceType" type="{http://www.onem2m.org/xml/protocols}resourceType" minOccurs="0"/>
 *         &lt;element name="sizeAbove" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="sizeBelow" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="contentType" type="{http://www.onem2m.org/xml/protocols}typeOfContent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="attribute" type="{http://www.onem2m.org/xml/protocols}attribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="filterUsage" type="{http://www.onem2m.org/xml/protocols}filterUsage" minOccurs="0"/>
 *         &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filterCriteria", propOrder = {
    "createdBefore",
    "createdAfter",
    "modifiedSince",
    "unmodifiedSince",
    "stateTagSmaller",
    "stateTagBigger",
    "expireBefore",
    "expireAfter",
    "labels",
    "resourceType",
    "sizeAbove",
    "sizeBelow",
    "contentType",
    "attribute",
    "filterUsage",
    "limit",
    "semanticsFilter",			// added in CDT-2.7.0
    "filterOperation",			// added in CDT-2.7.0
    "contentFilterSyntax",		// added in CDT-2.7.0	
    "contentFilterQuery",		// added in CDT-2.7.0
    "level",					// added in CDT-2.7.0
    "offset"					// added in CDT-2.7.0
})
public class FilterCriteria {

    @XmlElement(name = Naming.CREATEDBEFORE_SN)
    protected String createdBefore;
    @XmlElement(name = Naming.CREATEDAFTER_SN)
    protected String createdAfter;
    @XmlElement(name = Naming.MODIFIEDSINCE_SN)
    protected String modifiedSince;
    @XmlElement(name = Naming.UNMODIFIEDSINCE_SN)
    protected String unmodifiedSince;
    @XmlElement(name = Naming.STATETAGSMALLER_SN)
    @XmlSchemaType(name = "positiveInteger")
    protected Integer stateTagSmaller;
    @XmlElement(name = Naming.STATETAGBIGGER_SN)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer stateTagBigger;
    @XmlElement(name = Naming.EXPIREBEFORE_SN)
    protected String expireBefore;
    @XmlElement(name = Naming.EXPIREAFTER_SN)
    protected String expireAfter;
    @XmlElement(name = Naming.LABELS_SN)
    @XmlList
    protected List<String> labels;
    @XmlElement(name = Naming.FCRESOURCETYPE_SN)
    protected List<Integer> resourceType;
    @XmlElement(name = Naming.SIZEABOVE_SN)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer sizeAbove;
    @XmlElement(name = Naming.SIZEBELOW_SN)
    @XmlSchemaType(name = "positiveInteger")
    protected Integer sizeBelow;
    @XmlElement(name = Naming.CONTENTTYPE_SN)
    protected List<String> contentType;
    @XmlElement(name = Naming.ATTRIBUTE_SN)
    protected List<Attribute> attribute;
    @XmlElement(name = Naming.FILTERUSAGE_SN)
    protected Integer filterUsage;
    @XmlSchemaType(name = "nonNegativeInteger")
    @XmlElement(name = Naming.LIMIT_SN)
    protected Integer limit;
    @XmlElement(name = Naming.SEMANTICSFILTER_SN)
    protected List<String> semanticsFilter;				// added in CDT-2.7.0
    @XmlElement(name = Naming.FILTEROPERATION_SN)
    protected Integer filterOperation;					// added in CDT-2.7.0
    @XmlElement(name = Naming.CONTENTFILTERSYNTAX_SN)
    protected Integer contentFilterSyntax;				// added in CDT-2.7.0
    @XmlElement(name = Naming.CONTENTFILTERQUERY_SN)
    protected String contentFilterQuery;				// added in CDT-2.7.0
    @XmlElement(name = Naming.LEVEL_SN)
    @XmlSchemaType(name = "positiveInteger")				
    protected Integer level;							// added in CDT-2.7.0
    @XmlElement(name = Naming.OFFSET_SN)
    @XmlSchemaType(name = "positiveInteger")
    protected Integer offset;							// added in CDT-2.7.0


    public String toString() {
		StringBuilder bld = new StringBuilder();

		bld.append(" FilterCriteria ").append("\n");
		bld.append("  .CreatedBefore:").append(createdBefore).append("\n");
		bld.append("  .CreatedAfter:").append(createdAfter).append("\n");
		bld.append("  .ModifiedSince:").append(modifiedSince).append("\n");
		bld.append("  .UnmodifiedSince:").append(unmodifiedSince).append("\n");
		bld.append("  .StateTagSmaller:").append(stateTagSmaller).append("\n");
		bld.append("  .StateTagBigger:").append(stateTagBigger).append("\n");
		bld.append("  .ExpireBefore:").append(expireBefore).append("\n");
		bld.append("  .ExpireAfter:").append(expireAfter).append("\n");
		bld.append("  .Labels:").append(labels).append("\n");
		bld.append("  .resourceType:").append(resourceType).append("\n");
		bld.append("  .SizeAbove:").append(sizeAbove).append("\n");
		bld.append("  .SizeBelow:").append(sizeBelow).append("\n");
		bld.append("  .ContentType:").append(contentType).append("\n");
		bld.append("  .Attribute:").append(attribute).append("\n");
		bld.append("  .FilterUsage:").append(filterUsage).append("\n");
		bld.append("  .Limit:").append(limit).append("\n");
		bld.append("  .SemanticsFilter:").append(semanticsFilter).append("\n");
		bld.append("  .FilterOperation:").append(filterOperation).append("\n");
		bld.append("  .ContentFilterSyntax:").append(contentFilterSyntax).append("\n");
		bld.append("  .ContentFilterQuery:").append(contentFilterQuery).append("\n");
		bld.append("  .Level:").append(level).append("\n");
		bld.append("  .Offset:").append(offset).append("\n");
		
		return bld.toString();
	}
    
    
    /**
     * Gets the value of the createdBefore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedBefore() {
        return createdBefore;
    }

    /**
     * Sets the value of the createdBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedBefore(String value) {
        this.createdBefore = value;
    }

    /**
     * Gets the value of the createdAfter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatedAfter() {
        return createdAfter;
    }

    /**
     * Sets the value of the createdAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedAfter(String value) {
        this.createdAfter = value;
    }

    /**
     * Gets the value of the modifiedSince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedSince() {
        return modifiedSince;
    }

    /**
     * Sets the value of the modifiedSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedSince(String value) {
        this.modifiedSince = value;
    }

    /**
     * Gets the value of the unmodifiedSince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnmodifiedSince() {
        return unmodifiedSince;
    }

    /**
     * Sets the value of the unmodifiedSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnmodifiedSince(String value) {
        this.unmodifiedSince = value;
    }

    /**
     * Gets the value of the stateTagSmaller property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStateTagSmaller() {
        return stateTagSmaller;
    }

    /**
     * Sets the value of the stateTagSmaller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStateTagSmaller(Integer value) {
        this.stateTagSmaller = value;
    }

    /**
     * Gets the value of the stateTagBigger property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStateTagBigger() {
        return stateTagBigger;
    }

    /**
     * Sets the value of the stateTagBigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStateTagBigger(Integer value) {
        this.stateTagBigger = value;
    }

    /**
     * Gets the value of the expireBefore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireBefore() {
        return expireBefore;
    }

    /**
     * Sets the value of the expireBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireBefore(String value) {
        this.expireBefore = value;
    }

    /**
     * Gets the value of the expireAfter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireAfter() {
        return expireAfter;
    }

    /**
     * Sets the value of the expireAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireAfter(String value) {
        this.expireAfter = value;
    }

    /**
     * Gets the value of the labels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLabels() {
//    	if (labels == null) {
//    		labels = new ArrayList<String>();
//    	}
    	return this.labels;
    }
    
    public void addLabels(String lb) {
    	if (labels == null) {
    		labels = new ArrayList<String>();
    	}
    	this.labels.add(lb);
    }


    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public List<Integer> getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void addResourceType(Integer value) {
    	if(resourceType == null) {
    		resourceType = new ArrayList<Integer>();
    	}
        this.resourceType.add(value);
    }

    /**
     * Gets the value of the sizeAbove property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSizeAbove() {
        return sizeAbove;
    }

    /**
     * Sets the value of the sizeAbove property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSizeAbove(Integer value) {
        this.sizeAbove = value;
    }

    /**
     * Gets the value of the sizeBelow property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSizeBelow() {
        return sizeBelow;
    }

    /**
     * Sets the value of the sizeBelow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSizeBelow(Integer value) {
        this.sizeBelow = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContentType() {
//    	if (contentType == null) {
//    		contentType = new ArrayList<String>();
//    	}
    	return this.contentType;
    }

    public void addContentType(String cnt) {
    	if (contentType == null) {
    		contentType = new ArrayList<String>();
    	}
    	this.contentType.add(cnt);
    }
    
    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    public List<Attribute> getAttribute() {
    	if (attribute == null) {
    		attribute = new ArrayList<Attribute>();
    	}
    	return this.attribute;
    }
    
    public void addAttribute(Attribute attr) {
    	if (attribute == null) {
    		attribute = new ArrayList<Attribute>();
    	}
    	this.attribute.add(attr);
    }

    /**
     * Gets the value of the filterUsage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFilterUsage() {
        return filterUsage;
    }

    /**
     * Sets the value of the filterUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFilterUsage(Integer value) {
        this.filterUsage = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLimit(Integer value) {
        this.limit = value;
    }
    
    /**
     * Gets the value of the semanticsFilter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the semanticsFilter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSemanticsFilter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSemanticsFilter() {
     //   if (semanticsFilter == null) {
     //      semanticsFilter = new ArrayList<String>();
     //   }
        return this.semanticsFilter;
    }
    
    public void addSemanticsFilter(String value) {
    	if (semanticsFilter == null) {
    		semanticsFilter = new ArrayList<String>();
    	}
    	this.semanticsFilter.add(value);
    }

    /**
     * Gets the value of the filterOperation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Integer getFilterOperation() {
        return filterOperation;
    }

    /**
     * Sets the value of the filterOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFilterOperation(Integer value) {
        this.filterOperation = value;
    }

    /**
     * Gets the value of the contentFilterSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getContentFilterSyntax() {
        return contentFilterSyntax;
    }

    /**
     * Sets the value of the contentFilterSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setContentFilterSyntax(Integer value) {
        this.contentFilterSyntax = value;
    }

    /**
     * Gets the value of the contentFilterQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentFilterQuery() {
        return contentFilterQuery;
    }

    /**
     * Sets the value of the contentFilterQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentFilterQuery(String value) {
        this.contentFilterQuery = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLevel(Integer value) {
        this.level = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOffset(Integer value) {
        this.offset = value;
    }

}
