//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.07 at 09:56:03 AM KST 
//


package net.herit.iot.onem2m.resource;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for announcedFlexContainerResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="announcedFlexContainerResource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceType" type="{http://www.onem2m.org/xml/protocols}resourceType"/>
 *         &lt;element name="resourceID" type="{http://www.onem2m.org/xml/protocols}ID"/>
 *         &lt;element name="parentID" type="{http://www.onem2m.org/xml/protocols}nhURI"/>
 *         &lt;element name="creationTime" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="lastModifiedTime" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="labels" type="{http://www.onem2m.org/xml/protocols}labels" minOccurs="0"/>
 *         &lt;element name="accessControlPolicyIDs" type="{http://www.onem2m.org/xml/protocols}acpType"/>
 *         &lt;element name="expirationTime" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="dynamicAuthorizationConsultationIDs" type="{http://www.onem2m.org/xml/protocols}listOfURIs" minOccurs="0"/>
 *         &lt;element name="stateTag" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="containerDefinition" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="ontologyRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="resourceName" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "announcedFlexContainerResource", propOrder = {
    "resourceType",
    "resourceID",
    "parentID",
    "creationTime",
    "lastModifiedTime",
    "labels",
    "accessControlPolicyIDs",
    "expirationTime",
    "link",
    "dynamicAuthorizationConsultationIDs",
    "stateTag",
    "containerDefinition",
    "ontologyRef"
})
@XmlSeeAlso({
    AllJoynMethodAnnc.class,
    AllJoynInterfaceAnnc.class,
    AllJoynAppAnnc.class,
    SvcObjWrapperAnnc.class,
    AllJoynMethodCallAnnc.class,
    SvcFwWrapperAnnc.class,
    AllJoynSvcObjectAnnc.class,
    AllJoynPropertyAnnc.class,
    GenericInterworkingOperationInstanceAnnc.class,
    GenericInterworkingServiceAnnc.class
})
public class AnnouncedFlexContainerResource {

    //@XmlElement(required = true)
	@XmlElement(name = Naming.RESOURCETYPE_SN, required = true)
    protected Integer resourceType;
    //@XmlElement(required = true)
	@XmlElement(name = Naming.RESOURCEID_SN, required = true)
    protected String resourceID;
    //@XmlElement(required = true)
	@XmlElement(name = Naming.PARENTID_SN, required = true)
    protected String parentID;
	@XmlElement(name = Naming.CREATIONTIME_SN)
    protected String creationTime;
	@XmlElement(name = Naming.LASTMODIFIEDTIME_SN)
    protected String lastModifiedTime;
    @XmlList
    @XmlElement(name = Naming.LABELS_SN)
    protected List<String> labels;
    @XmlList
    @XmlElement(name = Naming.ACCESSCONTROLPOLICYIDS_SN, required = true)
    //@XmlElement(required = true)
    protected List<String> accessControlPolicyIDs;
    @XmlElement(name = Naming.EXPIRATIONTIME_SN)
    protected String expirationTime;
    //@XmlElement(required = true)
    @XmlElement(name = Naming.LINK_SN, required = true)
    @XmlSchemaType(name = "anyURI")
    protected String link;
    @XmlList
    @XmlElement(name = Naming.DYNAMICAUTHORIZATIONCONSULTATIONIDS_SN)
    protected List<String> dynamicAuthorizationConsultationIDs;
    @XmlElement(name = Naming.STATETAG_SN)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer stateTag;
    @XmlElement(name = Naming.CONTAINERDEFINITION_SN, required = true)
    //@XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String containerDefinition;
    @XmlElement(name = Naming.ONTOLOGYREF_SN)
    @XmlSchemaType(name = "anyURI")
    protected String ontologyRef;
    @XmlElement(name = Naming.RESOURCENAME_SN)
    @XmlAttribute(name = "resourceName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String resourceName;

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResourceType(Integer value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the resourceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceID() {
        return resourceID;
    }

    /**
     * Sets the value of the resourceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceID(String value) {
        this.resourceID = value;
    }

    /**
     * Gets the value of the parentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentID() {
        return parentID;
    }

    /**
     * Sets the value of the parentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentID(String value) {
        this.parentID = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationTime(String value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModifiedTime(String value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the labels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLabels() {
      //  if (labels == null) {
      //      labels = new ArrayList<String>();
      //  }
        return this.labels;
    }
    
    public void addLabels(String value) {
    	if (labels == null) {
    		labels = new ArrayList<String>();
    	}
    	this.labels.add(value);
    }

    /**
     * Gets the value of the accessControlPolicyIDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessControlPolicyIDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessControlPolicyIDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAccessControlPolicyIDs() {
        //if (accessControlPolicyIDs == null) {
        //    accessControlPolicyIDs = new ArrayList<String>();
        //}
        return this.accessControlPolicyIDs;
    }
    
    public void addAccessControlPolicyIDs(String value) {
    	if (accessControlPolicyIDs == null) {
    		accessControlPolicyIDs = new ArrayList<String>();
    	}
    	this.accessControlPolicyIDs.add(value);
    }

    /**
     * Gets the value of the expirationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationTime() {
        return expirationTime;
    }

    /**
     * Sets the value of the expirationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationTime(String value) {
        this.expirationTime = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the dynamicAuthorizationConsultationIDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dynamicAuthorizationConsultationIDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDynamicAuthorizationConsultationIDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDynamicAuthorizationConsultationIDs() {
        //if (dynamicAuthorizationConsultationIDs == null) {
        //    dynamicAuthorizationConsultationIDs = new ArrayList<String>();
        //}
        return this.dynamicAuthorizationConsultationIDs;
    }
    
    public void addDynamicAuthorizationConsultationIDs(String value) {
    	if (dynamicAuthorizationConsultationIDs == null) {
    		dynamicAuthorizationConsultationIDs = new ArrayList<String>();
    	}
    	this.dynamicAuthorizationConsultationIDs.add(value);
    }

    /**
     * Gets the value of the stateTag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStateTag() {
        return stateTag;
    }

    /**
     * Sets the value of the stateTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStateTag(Integer value) {
        this.stateTag = value;
    }

    /**
     * Gets the value of the containerDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerDefinition() {
        return containerDefinition;
    }

    /**
     * Sets the value of the containerDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerDefinition(String value) {
        this.containerDefinition = value;
    }

    /**
     * Gets the value of the ontologyRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntologyRef() {
        return ontologyRef;
    }

    /**
     * Sets the value of the ontologyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntologyRef(String value) {
        this.ontologyRef = value;
    }

    /**
     * Gets the value of the resourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * Sets the value of the resourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceName(String value) {
        this.resourceName = value;
    }

}
