//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 03:04:20 오후 KST 
//


package net.herit.iot.onem2m.resource;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import net.herit.iot.message.onem2m.OneM2mRequest.OPERATION;
import net.herit.iot.message.onem2m.OneM2mResponse.RESPONSE_STATUS;
import net.herit.iot.onem2m.core.util.OneM2MException;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}mgmtResource">
 *       &lt;sequence>
 *         &lt;element name="applicableEventCategory" type="{http://www.onem2m.org/xml/protocols}listOfEventCatWithDef"/>
 *         &lt;element name="maxBufferSize" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="storagePriority">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;maxExclusive value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicableEventCategory",
    "maxBufferSize",
    "storagePriority"
})
//@XmlRootElement(name = "cmdhBuffer")
@XmlRootElement(name = "cmbf")
public class CmdhBuffer
    extends MgmtResource
{

//	public final static String SCHEMA_LOCATION = "CDT-cmdhBuffer-v1_2_0.xsd";
	public final static String SCHEMA_LOCATION = "CDT-cmdhBuffer-v1_6_0.xsd";
	
    @XmlList
    //@XmlElement(required = true)
    @XmlElement(name = "aec", required = true)
    protected List<String> applicableEventCategory;
    //@XmlElement(required = true)
    @XmlElement(name = "mbfs", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer maxBufferSize;
    @XmlElement(name = "sgp")
    protected Integer storagePriority;

    /**
     * Gets the value of the applicableEventCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicableEventCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicableEventCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getApplicableEventCategory() {
//        if (applicableEventCategory == null) {
//            applicableEventCategory = new ArrayList<String>();
//        }
        return this.applicableEventCategory;
    }

    public void addApplicableEventCategory(String avc) {
    	if (applicableEventCategory == null) {
    		applicableEventCategory = new ArrayList<String>();
    	}
    	this.applicableEventCategory.add(avc);
    }
    
    /**
     * Gets the value of the maxBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxBufferSize() {
        return maxBufferSize;
    }

    /**
     * Sets the value of the maxBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxBufferSize(Integer value) {
        this.maxBufferSize = value;
    }

    /**
     * Gets the value of the storagePriority property.
     * 
     */
    public int getStoragePriority() {
        return storagePriority;
    }

    /**
     * Sets the value of the storagePriority property.
     * 
     */
    public void setStoragePriority(int value) {
        this.storagePriority = value;
    }


    @Override
	public void validate(OPERATION operation) throws OneM2MException {
		
		if (operation.equals(OPERATION.CREATE)) {	// create 요청에 의해 생성된 리소스에 대한 유효성 체크 (DB저장전)

			if (this.mgmtDefinition == null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'mgmtDefinition' is M on CREATE operation");
			}
			if (this.applicableEventCategory == null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'applicableEventCategory' is M on CREATE operation");
			}
			if (this.maxBufferSize == null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'maxBufferSize' is M on CREATE operation");
			}
			if (this.storagePriority == null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'storagePriority' is M on CREATE operation");
			}
			
		} else if (operation.equals(OPERATION.UPDATE)) {	// update 요청에 의해 생성된 리소스에 대한 유효성 체크 (DB저장전)
			
			if (this.mgmtDefinition != null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'mgmtDefinition' is NP on UPDATE operation");
			}
			if (this.objectIDs != null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'objectIDs' is NP on UPDATE operation");
			}
			if (this.objectPaths != null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'objectPaths' is NP on UPDATE operation");
			}
			
		}
	
		super.validate(operation);
		
	}
}
