//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 03:14:16 오후 KST 
//


package net.herit.iot.onem2m.resource;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * XSD-1.6.0
 * <p>Java class for execReqArgsListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="execReqArgsListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="reset" type="{http://www.onem2m.org/xml/protocols}resetArgsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reboot" type="{http://www.onem2m.org/xml/protocols}rebootArgsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="upload" type="{http://www.onem2m.org/xml/protocols}uploadArgsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="download" type="{http://www.onem2m.org/xml/protocols}downloadArgsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="softwareInstall" type="{http://www.onem2m.org/xml/protocols}softwareInstallArgsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="softwareUpdate" type="{http://www.onem2m.org/xml/protocols}softwareUpdateArgsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="softwareUninstall" type="{http://www.onem2m.org/xml/protocols}softwareUninstallArgsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "execReqArgsListType", propOrder = {
    "reset",
    "reboot",
    "upload",
    "download",
    "softwareInstall",
    "softwareUpdate",
    "softwareUninstall"
})
public class ExecReqArgsListType {

    @XmlElement(name = Naming.RESET_SN)
    protected List<ResetArgsType> reset;
    @XmlElement(name = Naming.REBOOT_SN)
    protected List<RebootArgsType> reboot;
    @XmlElement(name = Naming.UPLOAD_SN)
    protected List<UploadArgsType> upload;
    @XmlElement(name = Naming.DOWNLOAD_SN)
    protected List<DownloadArgsType> download;
    @XmlElement(name = Naming.SOFTWAREINSTALL_SN)
    protected List<SoftwareInstallArgsType> softwareInstall;
    @XmlElement(name = Naming.SOFTWAREUPDATE_SN)
    protected List<SoftwareUpdateArgsType> softwareUpdate;
    @XmlElement(name = Naming.SOFTWAREUNINSTALL_SN)
    protected List<SoftwareUninstallArgsType> softwareUninstall;

    /**
     * Gets the value of the reset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResetArgsType }
     * 
     * 
     */
    public List<ResetArgsType> getReset() {
//    	if (reset == null) {
//    		reset = new ArrayList<ResetArgsType>();
//    	}
    	return this.reset;
    }

    public void addReset(ResetArgsType rst) {
    	if (reset == null) {
    		reset = new ArrayList<ResetArgsType>();
    	}
    	this.reset.add(rst);
    }
    
    /**
     * Gets the value of the reboot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reboot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReboot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RebootArgsType }
     * 
     * 
     */
    public List<RebootArgsType> getReboot() {
//    	if (reboot == null) {
//    		reboot = new ArrayList<RebootArgsType>();
//    	}
    	return this.reboot;
    }
    
    public void addReboot(RebootArgsType arg) {
    	if (reboot == null) {
    		reboot = new ArrayList<RebootArgsType>();
    	}
    	this.reboot.add(arg);
    }

    /**
     * Gets the value of the upload property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the upload property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpload().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UploadArgsType }
     * 
     * 
     */
    public List<UploadArgsType> getUpload() {
//    	if (upload == null) {
//    		upload = new ArrayList<UploadArgsType>();
//    	}
    	return this.upload;
    }
    
    public void addUpload(UploadArgsType arg) {
    	if (upload == null) {
    		upload = new ArrayList<UploadArgsType>();
    	}
    	this.upload.add(arg);
    }


    /**
     * Gets the value of the download property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the download property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDownload().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DownloadArgsType }
     * 
     * 
     */
    public List<DownloadArgsType> getDownload() {
//    	if (download == null) {
//    		download = new ArrayList<DownloadArgsType>();
//    	}
    	return this.download;
    }

    public void addDownload(DownloadArgsType type) {
    	if (download == null) {
    		download = new ArrayList<DownloadArgsType>();
    	}
    	this.download.add(type);
    }
    
    /**
     * Gets the value of the softwareInstall property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the softwareInstall property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoftwareInstall().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoftwareInstallArgsType }
     * 
     * 
     */
    public List<SoftwareInstallArgsType> getSoftwareInstall() {
//    	if (softwareInstall == null) {
//    		softwareInstall = new ArrayList<SoftwareInstallArgsType>();
//    	}
    	return this.softwareInstall;
    }

    public void addSoftwareInstall(SoftwareInstallArgsType type) {
    	if (softwareInstall == null) {
    		softwareInstall = new ArrayList<SoftwareInstallArgsType>();
    	}
    	this.softwareInstall.add(type);
    }
    
    /**
     * Gets the value of the softwareUpdate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the softwareUpdate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoftwareUpdate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoftwareUpdateArgsType }
     * 
     * 
     */
    public List<SoftwareUpdateArgsType> getSoftwareUpdate() {
//    	if (softwareUpdate == null) {
//    		softwareUpdate = new ArrayList<SoftwareUpdateArgsType>();
//    	}
    	return this.softwareUpdate;
    }

    public void addSoftwareUpdate(SoftwareUpdateArgsType type) {
    	if (softwareUpdate == null) {
    		softwareUpdate = new ArrayList<SoftwareUpdateArgsType>();
    	}
    	this.softwareUpdate.add(type);
    }

    
    /**
     * Gets the value of the softwareUninstall property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the softwareUninstall property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoftwareUninstall().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoftwareUninstallArgsType }
     * 
     * 
     */
    public List<SoftwareUninstallArgsType> getSoftwareUninstall() {
//    	if (softwareUninstall == null) {
//    		softwareUninstall = new ArrayList<SoftwareUninstallArgsType>();
//    	}
    	return this.softwareUninstall;
    }
    
    public void addSoftwareUninstall(SoftwareUninstallArgsType type) {
    	if (softwareUninstall == null) {
    		softwareUninstall = new ArrayList<SoftwareUninstallArgsType>();
    	}
    	this.softwareUninstall.add(type);
    }


}
