//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 03:13:54 오후 KST 
//


package net.herit.iot.onem2m.resource;


import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;

import net.herit.iot.message.onem2m.OneM2mRequest.OPERATION;
import net.herit.iot.message.onem2m.OneM2mResponse.RESPONSE_STATUS;
import net.herit.iot.onem2m.core.util.OneM2MException;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}regularResource">
 *       &lt;sequence>
 *         &lt;element name="execStatus" type="{http://www.onem2m.org/xml/protocols}execStatusType"/>
 *         &lt;element name="execResult" type="{http://www.onem2m.org/xml/protocols}execResultType"/>
 *         &lt;element name="execDisable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="execTarget" type="{http://www.onem2m.org/xml/protocols}nodeID"/>
 *         &lt;element name="execMode" type="{http://www.onem2m.org/xml/protocols}execModeType" minOccurs="0"/>
 *         &lt;element name="execFrequency" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="execDelay" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="execNumber" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="execReqArgs" type="{http://www.onem2m.org/xml/protocols}execReqArgsListType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "execStatus",
    "execResult",
    "execDisable",
    "execTarget",
    "execMode",
    "execFrequency",
    "execDelay",
    "execNumber",
    "execReqArgs",
    "childResource",
    "subscription"
})
//@XmlRootElement(name = "execInstance")
@XmlRootElement(name = "exin")
public class ExecInstance
    extends RegularResource
{

//	public static final String SCHEMA_LOCATION = "CDT-execInstance-v1_2_0.xsd";
	public static final String SCHEMA_LOCATION = "CDT-execInstance-v1_6_0.xsd";
	
    //@XmlElement(required = true)
    @XmlElement(name = "exs")
    protected Integer execStatus;
    //@XmlElement(required = true)
    @XmlElement(name = "exr")
    protected Integer execResult;
    @XmlElement(name = "exd")
    protected Boolean execDisable;
    //@XmlElement(required = true)
    @XmlElement(name = "ext")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String execTarget;
    @XmlElement(name = "exm")
    protected Integer execMode;
    @XmlElement(name = "exf")
    protected Duration execFrequency;
    @XmlElement(name = "exy")
    protected Duration execDelay;
    @XmlElement(name = "exn")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer execNumber;
    @XmlElement(name = "exra")
    protected ExecReqArgsListType execReqArgs;
    @XmlElement(name = "ch")
    protected List<ChildResourceRef> childResource;
    @XmlElement(name = "sub", namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Subscription> subscription;

    /**
     * Gets the value of the execStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExecStatus() {
        return execStatus;
    }

    /**
     * Sets the value of the execStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExecStatus(Integer value) {
        this.execStatus = value;
    }

    /**
     * Gets the value of the execResult property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExecResult() {
        return execResult;
    }

    /**
     * Sets the value of the execResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExecResult(Integer value) {
        this.execResult = value;
    }

    /**
     * Gets the value of the execDisable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExecDisable() {
        return execDisable;
    }

    /**
     * Sets the value of the execDisable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExecDisable(Boolean value) {
        this.execDisable = value;
    }

    /**
     * Gets the value of the execTarget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecTarget() {
        return execTarget;
    }

    /**
     * Sets the value of the execTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecTarget(String value) {
        this.execTarget = value;
    }

    /**
     * Gets the value of the execMode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExecMode() {
        return execMode;
    }

    /**
     * Sets the value of the execMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExecMode(Integer value) {
        this.execMode = value;
    }

    /**
     * Gets the value of the execFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getExecFrequency() {
        return execFrequency;
    }

    /**
     * Sets the value of the execFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setExecFrequency(Duration value) {
        this.execFrequency = value;
    }

    /**
     * Gets the value of the execDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getExecDelay() {
        return execDelay;
    }

    /**
     * Sets the value of the execDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setExecDelay(Duration value) {
        this.execDelay = value;
    }

    /**
     * Gets the value of the execNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExecNumber() {
        return execNumber;
    }

    /**
     * Sets the value of the execNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExecNumber(Integer value) {
        this.execNumber = value;
    }

    /**
     * Gets the value of the execReqArgs property.
     * 
     * @return
     *     possible object is
     *     {@link ExecReqArgsListType }
     *     
     */
    public ExecReqArgsListType getExecReqArgs() {
        return execReqArgs;
    }

    /**
     * Sets the value of the execReqArgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecReqArgsListType }
     *     
     */
    public void setExecReqArgs(ExecReqArgsListType value) {
        this.execReqArgs = value;
    }

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
//    	if (childResource == null) {
//    		childResource = new ArrayList<ChildResourceRef>();
//    	}
    	return this.childResource;
    }

    public void addChildResource(ChildResourceRef ch) {
    	if (childResource == null) {
    		childResource = new ArrayList<ChildResourceRef>();
    	}
    	this.childResource.add(ch);
    }
    
    /**
     * Gets the value of the subscription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subscription }
     * 
     * 
     */
    public List<Subscription> getSubscription() {
//    	if (subscription == null) {
//    		subscription = new ArrayList<Subscription>();
//    	}
    	return this.subscription;
    }

    public void addSubscription(Subscription sub) {
    	if (subscription == null) {
    		subscription = new ArrayList<Subscription>();
    	}
    	this.subscription.add(sub);
    }
    

    @Override
	public void validate(OPERATION operation) throws OneM2MException {
		
		if (operation.equals(OPERATION.CREATE)) {	// create 요청에 의해 생성된 리소스에 대한 유효성 체크 (DB저장전)

			if (this.execStatus != null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'execStatus' is NP on CREATE operation");
			}
			if (this.execResult != null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'execResult' is NP on CREATE operation");
			}
			if (this.execDisable != null) {
				throw new OneM2MException(RESPONSE_STATUS.INVALID_ARGUMENTS, "'execDisable' is NP on CREATE operation");
			}
			
		} else if (operation.equals(OPERATION.UPDATE)) {	// update 요청에 의해 생성된 리소스에 대한 유효성 체크 (DB저장전)
		}
	
		super.validate(operation);
		
	}
}
