//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 03:14:07 오후 KST 
//


package net.herit.iot.onem2m.resource;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedResource">
 *       &lt;sequence>
 *         &lt;element name="locationSource" type="{http://www.onem2m.org/xml/protocols}locationSource" minOccurs="0"/>
 *         &lt;element name="locationUpdatePeriod" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="locationTargetID" type="{http://www.onem2m.org/xml/protocols}nodeID" minOccurs="0"/>
 *         &lt;element name="locationServer" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="locationContainerID" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="locationContainerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="locationStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locationSource",
    "locationUpdatePeriod",
    "locationTargetID",
    "locationServer",
    "locationContainerID",
    "locationContainerName",
    "locationStatus"
})
//@XmlRootElement(name = "locationPolicyAnnc")
@XmlRootElement(name = "m2m:" +  Naming.LOCATIONPOLICYANNC_SN)
public class LocationPolicyAnnc
    extends AnnouncedResource
{

//	public final static String SCHEMA_LOCATION = "CDT-locationPolicy-v1_2_0.xsd";
//	public final static String SCHEMA_LOCATION = "CDT-locationPolicy-v1_6_0.xsd";
	public final static String SCHEMA_LOCATION = "CDT-locationPolicy-v2_7_0.xsd";
	
	public static final List<String> MA = new ArrayList<String>(
		Arrays.asList(Naming.RESOURCEID_SN,
						Naming.RESOURCENAME_SN,
						Naming.EXPIRATIONTIME_SN,
						Naming.ACCESSCONTROLPOLICYIDS_SN,
						Naming.LABELS_SN
		)
	);
	public static final Set<String> OA = new HashSet<String>(
		Arrays.asList(Naming.LOCATIONSOURCE_SN,
						Naming.LOCATIONUPDATEPERIOD_SN,
						Naming.LOCATIONTARGETID_SN,
						Naming.LOCATIONSERVER_SN,
						Naming.LOCATIONCONTAINERID_SN,
						Naming.LOCATIONCONTAINERNAME_SN,
						Naming.LOCATIONSTATUS_SN
						
		)
	);

	
	
    @XmlElement(name = Naming.LOCATIONSOURCE_SN)
    protected Integer locationSource;
    @XmlElement(name = Naming.LOCATIONUPDATEPERIOD_SN)
    @XmlList
    protected List<Duration> locationUpdatePeriod;		// Data type changed from Duration to List<Duration> in CDT-2.7.0
    @XmlElement(name = Naming.LOCATIONTARGETID_SN)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String locationTargetID;
    @XmlElement(name = Naming.LOCATIONSERVER_SN)
    @XmlSchemaType(name = "anyURI")
    protected String locationServer;
    @XmlElement(name = Naming.LOCATIONCONTAINERID_SN)
    @XmlSchemaType(name = "anyURI")
    protected String locationContainerID;
    @XmlElement(name = Naming.LOCATIONCONTAINERNAME_SN)
    protected String locationContainerName;
    @XmlElement(name = Naming.LOCATIONSTATUS_SN)
    protected String locationStatus;

    /**
     * Gets the value of the locationSource property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLocationSource() {
        return locationSource;
    }

    /**
     * Sets the value of the locationSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLocationSource(Integer value) {
        this.locationSource = value;
    }

    /**
     * Gets the value of the locationUpdatePeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locationUpdatePeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationUpdatePeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Duration }
     * 
     * 
     */
    public List<Duration> getLocationUpdatePeriod() {
      //  if (locationUpdatePeriod == null) {
      //      locationUpdatePeriod = new ArrayList<Duration>();
      //  }
        return this.locationUpdatePeriod;
    }
    
    public void addLocationUpdatePeriod(Duration dur) {
    	if (locationUpdatePeriod == null) {
    		locationUpdatePeriod = new ArrayList<Duration>();
    	}
    	this.locationUpdatePeriod.add(dur);
    }

    /**
     * Gets the value of the locationTargetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationTargetID() {
        return locationTargetID;
    }

    /**
     * Sets the value of the locationTargetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationTargetID(String value) {
        this.locationTargetID = value;
    }

    /**
     * Gets the value of the locationServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationServer() {
        return locationServer;
    }

    /**
     * Sets the value of the locationServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationServer(String value) {
        this.locationServer = value;
    }

    /**
     * Gets the value of the locationContainerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationContainerID() {
        return locationContainerID;
    }

    /**
     * Sets the value of the locationContainerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationContainerID(String value) {
        this.locationContainerID = value;
    }

    /**
     * Gets the value of the locationContainerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationContainerName() {
        return locationContainerName;
    }

    /**
     * Sets the value of the locationContainerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationContainerName(String value) {
        this.locationContainerName = value;
    }

    /**
     * Gets the value of the locationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationStatus() {
        return locationStatus;
    }

    /**
     * Sets the value of the locationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationStatus(String value) {
        this.locationStatus = value;
    }

}
