//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.07 at 09:56:03 AM KST 
//


package net.herit.iot.onem2m.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for securityInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="securityInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="securityInfoType" type="{http://www.onem2m.org/xml/protocols}securityInfoType" minOccurs="0"/>
 *         &lt;element name="dasRequest" type="{http://www.onem2m.org/xml/protocols}dynAuthDasRequest" minOccurs="0"/>
 *         &lt;element name="dasResponse" type="{http://www.onem2m.org/xml/protocols}dynAuthDasResponse" minOccurs="0"/>
 *         &lt;element name="esprimRandObject" type="{http://www.onem2m.org/xml/protocols}receiverESPrimRandObject" minOccurs="0"/>
 *         &lt;element name="esprimObject" type="{http://www.onem2m.org/xml/protocols}e2eCompactJWE" minOccurs="0"/>
 *         &lt;element name="escertkeMessage" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "securityInfo", propOrder = {
    "securityInfoType",
    "dasRequest",
    "dasResponse",
    "esprimRandObject",
    "esprimObject",
    "escertkeMessage"
})
public class SecurityInfo {

	@XmlElement(name = Naming.SECURITYINFOTYPE_SN)
    protected Integer securityInfoType;
	@XmlElement(name = Naming.DASREQUEST_SN)
    protected DynAuthDasRequest dasRequest;
	@XmlElement(name = Naming.DASRESPONSE_SN)
    protected DynAuthDasResponse dasResponse;
	@XmlElement(name = Naming.ESPRIMRANDOBJECT_SN)
    protected ReceiverESPrimRandObject esprimRandObject;
	@XmlElement(name = Naming.ESPRIMOBJECT_SN)
    protected String esprimObject;
	@XmlElement(name = Naming.ESCERTKEMESSAGE_SN)
    protected byte[] escertkeMessage;

    /**
     * Gets the value of the securityInfoType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSecurityInfoType() {
        return securityInfoType;
    }

    /**
     * Sets the value of the securityInfoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSecurityInfoType(Integer value) {
        this.securityInfoType = value;
    }

    /**
     * Gets the value of the dasRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DynAuthDasRequest }
     *     
     */
    public DynAuthDasRequest getDasRequest() {
        return dasRequest;
    }

    /**
     * Sets the value of the dasRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynAuthDasRequest }
     *     
     */
    public void setDasRequest(DynAuthDasRequest value) {
        this.dasRequest = value;
    }

    /**
     * Gets the value of the dasResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DynAuthDasResponse }
     *     
     */
    public DynAuthDasResponse getDasResponse() {
        return dasResponse;
    }

    /**
     * Sets the value of the dasResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynAuthDasResponse }
     *     
     */
    public void setDasResponse(DynAuthDasResponse value) {
        this.dasResponse = value;
    }

    /**
     * Gets the value of the esprimRandObject property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverESPrimRandObject }
     *     
     */
    public ReceiverESPrimRandObject getEsprimRandObject() {
        return esprimRandObject;
    }

    /**
     * Sets the value of the esprimRandObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverESPrimRandObject }
     *     
     */
    public void setEsprimRandObject(ReceiverESPrimRandObject value) {
        this.esprimRandObject = value;
    }

    /**
     * Gets the value of the esprimObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsprimObject() {
        return esprimObject;
    }

    /**
     * Sets the value of the esprimObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsprimObject(String value) {
        this.esprimObject = value;
    }

    /**
     * Gets the value of the escertkeMessage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getEscertkeMessage() {
        return escertkeMessage;
    }

    /**
     * Sets the value of the escertkeMessage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setEscertkeMessage(byte[] value) {
        this.escertkeMessage = value;
    }

}
