//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.07 at 09:56:03 AM KST 
//


package net.herit.iot.onem2m.resource;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedResource">
 *       &lt;sequence>
 *         &lt;element name="stateTag" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="maxNrOfInstances" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="maxByteSize" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="maxInstanceAge" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="currentNrOfInstances" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="currentByteSize" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="periodicInterval" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="missingDataDetect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="missingDataList" type="{http://www.onem2m.org/xml/protocols}missingDataList" minOccurs="0"/>
 *         &lt;element name="missingDataCurrentNr" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="missingDataDetectTimer" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="ontologyRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}timeSeriesInstance"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}timeSeriesInstanceAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}semanticDescriptor"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}semanticDescriptorAnnc"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stateTag",
    "maxNrOfInstances",
    "maxByteSize",
    "maxInstanceAge",
    "currentNrOfInstances",
    "currentByteSize",
    "periodicInterval",
    "missingDataDetect",
    "missingDataList",
    "missingDataCurrentNr",
    "missingDataDetectTimer",
    "ontologyRef",
    "childResource",
    "timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription"
})
public class TimeSeriesAnnc
    extends AnnouncedResource
{

    @XmlSchemaType(name = "nonNegativeInteger")
    @XmlElement(name = Naming.STATETAG_SN)
    protected Integer stateTag;
    @XmlSchemaType(name = "nonNegativeInteger")
    @XmlElement(name = Naming.MAXNROFINSTANCES_SN)
    protected Integer maxNrOfInstances;
    @XmlSchemaType(name = "nonNegativeInteger")
    @XmlElement(name = Naming.MAXBYTESIZE_SN)
    protected Integer maxByteSize;
    @XmlSchemaType(name = "nonNegativeInteger")
    @XmlElement(name = Naming.MAXINSTANCEAGE_SN)
    protected Integer maxInstanceAge;
    //@XmlElement(required = true)
    @XmlElement(name = Naming.CURRENTNROFINSTANCES_SN, required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer currentNrOfInstances;
    //@XmlElement(required = true)
    @XmlElement(name = Naming.CURRENTBYTESIZE_SN, required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer currentByteSize;
    @XmlSchemaType(name = "nonNegativeInteger")
    @XmlElement(name = Naming.PERIODICINTERVAL_SN)
    protected Integer periodicInterval;
    @XmlElement(name = Naming.MISSINGDATADETECT_SN)
    protected Boolean missingDataDetect;
    @XmlList
    @XmlElement(name = Naming.MISSINGDATALIST_SN)
    protected List<String> missingDataList;
    @XmlSchemaType(name = "nonNegativeInteger")
    @XmlElement(name = Naming.MISSINGDATACURRENTNR_SN)
    protected Integer missingDataCurrentNr;
    @XmlSchemaType(name = "nonNegativeInteger")
    @XmlElement(name = Naming.MISSINGDATADETECTTIMER_SN)
    protected Integer missingDataDetectTimer;
    @XmlSchemaType(name = "anyURI")
    @XmlElement(name = Naming.ONTOLOGYREF_SN)
    protected String ontologyRef;
    @XmlElement(name = Naming.CHILDRESOURCE_SN)
    protected List<ChildResourceRef> childResource;
    @XmlElements({
        @XmlElement(name = Naming.TIMESERIESINSTANCE_SN, namespace = "http://www.onem2m.org/xml/protocols", type = TimeSeriesInstance.class),
        @XmlElement(name = Naming.TIMESERIESINSTANCEANNC_SN, namespace = "http://www.onem2m.org/xml/protocols", type = TimeSeriesInstanceAnnc.class),
        @XmlElement(name = Naming.SUBSCRIPTION_SN, namespace = "http://www.onem2m.org/xml/protocols", type = Subscription.class),
        @XmlElement(name = Naming.SEMANTICDESCRIPTOR_SN, namespace = "http://www.onem2m.org/xml/protocols", type = SemanticDescriptor.class),
        @XmlElement(name = Naming.SEMANTICDESCRIPTORANNC_SN, namespace = "http://www.onem2m.org/xml/protocols", type = SemanticDescriptorAnnc.class)
    })
    protected List<Resource> timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription;

    /**
     * Gets the value of the stateTag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStateTag() {
        return stateTag;
    }

    /**
     * Sets the value of the stateTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStateTag(Integer value) {
        this.stateTag = value;
    }

    /**
     * Gets the value of the maxNrOfInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxNrOfInstances() {
        return maxNrOfInstances;
    }

    /**
     * Sets the value of the maxNrOfInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxNrOfInstances(Integer value) {
        this.maxNrOfInstances = value;
    }

    /**
     * Gets the value of the maxByteSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxByteSize() {
        return maxByteSize;
    }

    /**
     * Sets the value of the maxByteSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxByteSize(Integer value) {
        this.maxByteSize = value;
    }

    /**
     * Gets the value of the maxInstanceAge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxInstanceAge() {
        return maxInstanceAge;
    }

    /**
     * Sets the value of the maxInstanceAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxInstanceAge(Integer value) {
        this.maxInstanceAge = value;
    }

    /**
     * Gets the value of the currentNrOfInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCurrentNrOfInstances() {
        return currentNrOfInstances;
    }

    /**
     * Sets the value of the currentNrOfInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCurrentNrOfInstances(Integer value) {
        this.currentNrOfInstances = value;
    }

    /**
     * Gets the value of the currentByteSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCurrentByteSize() {
        return currentByteSize;
    }

    /**
     * Sets the value of the currentByteSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCurrentByteSize(Integer value) {
        this.currentByteSize = value;
    }

    /**
     * Gets the value of the periodicInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPeriodicInterval() {
        return periodicInterval;
    }

    /**
     * Sets the value of the periodicInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPeriodicInterval(Integer value) {
        this.periodicInterval = value;
    }

    /**
     * Gets the value of the missingDataDetect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMissingDataDetect() {
        return missingDataDetect;
    }

    /**
     * Sets the value of the missingDataDetect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMissingDataDetect(Boolean value) {
        this.missingDataDetect = value;
    }

    /**
     * Gets the value of the missingDataList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the missingDataList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMissingDataList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMissingDataList() {
      //  if (missingDataList == null) {
      //      missingDataList = new ArrayList<String>();
      //  }
        return this.missingDataList;
    }
    
    public void addMissingDataList(String value) {
    	if (missingDataList == null) {
    		missingDataList = new ArrayList<String>();
    	}
    	this.missingDataList.add(value);
    }

    /**
     * Gets the value of the missingDataCurrentNr property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMissingDataCurrentNr() {
        return missingDataCurrentNr;
    }

    /**
     * Sets the value of the missingDataCurrentNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMissingDataCurrentNr(Integer value) {
        this.missingDataCurrentNr = value;
    }

    /**
     * Gets the value of the missingDataDetectTimer property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMissingDataDetectTimer() {
        return missingDataDetectTimer;
    }

    /**
     * Sets the value of the missingDataDetectTimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMissingDataDetectTimer(Integer value) {
        this.missingDataDetectTimer = value;
    }

    /**
     * Gets the value of the ontologyRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntologyRef() {
        return ontologyRef;
    }

    /**
     * Sets the value of the ontologyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntologyRef(String value) {
        this.ontologyRef = value;
    }

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
      //  if (childResource == null) {
      //      childResource = new ArrayList<ChildResourceRef>();
      //  }
        return this.childResource;
    }
    
    public void addChildResource(ChildResourceRef value) {
    	if (childResource == null) {
    		childResource = new ArrayList<ChildResourceRef>();
    	}
    	this.childResource.add(value);
    }

    /**
     * Gets the value of the timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeSeriesInstance }
     * {@link TimeSeriesInstanceAnnc }
     * {@link Subscription }
     * {@link SemanticDescriptor }
     * {@link SemanticDescriptorAnnc }
     * 
     * 
     */
    public List<Resource> getTimeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription() {
      //  if (timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription == null) {
      //      timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription = new ArrayList<Resource>();
      //  }
        return this.timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription;
    }
    
    public void addTimeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription(Resource value) {
    	if (timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription == null) {
    		timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription = new ArrayList<Resource>();
    	}
    	this.timeSeriesInstanceOrTimeSeriesInstanceAnncOrSubscription.add(value);
    }

}
